import { MenuItem, Mode } from './types';

export const pizzaItems: MenuItem[] = [
  {
    id: 'margherita',
    name: 'Margherita',
    description: 'Fresh mozzarella, basil, tomato sauce',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=margherita+pizza',
    calories: '250-300 cal/slice',
    dietary: ['vegetarian'],
    popular: true,
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['comfort', 'light'],
      style: ['classic'],
    },
  },
  {
    id: 'pepperoni',
    name: 'Pepperoni',
    description: 'Classic pepperoni with mozzarella',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=pepperoni+pizza',
    calories: '300-350 cal/slice',
    dietary: [],
    popular: true,
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'bbq-chicken',
    name: 'BBQ Chicken',
    description: 'Grilled chicken, BBQ sauce, red onions',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=bbq+chicken+pizza',
    calories: '320-370 cal/slice',
    dietary: ['dairy-free'],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['comfort'],
      style: ['adventurous'],
    },
  },
  {
    id: 'veggie',
    name: 'Veggie Supreme',
    description: 'Bell peppers, mushrooms, olives, onions',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=veggie+supreme+pizza',
    calories: '220-270 cal/slice',
    dietary: ['vegetarian', 'vegan'],
    popular: true,
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['light'],
      style: ['classic', 'adventurous'],
    },
  },
  {
    id: 'spicy-chicken',
    name: 'Spicy Chicken',
    description: 'Jalapeños, hot sauce, grilled chicken',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=spicy+chicken+pizza',
    calories: '310-360 cal/slice',
    dietary: [],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['spicy'],
      style: ['adventurous'],
    },
  },
  {
    id: 'truffle-mushroom',
    name: 'Truffle Mushroom',
    description: 'Wild mushrooms, truffle oil, arugula',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=truffle+mushroom+pizza',
    calories: '280-330 cal/slice',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['comfort', 'light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'hawaiian',
    name: 'Hawaiian',
    description: 'Ham, pineapple, mozzarella',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=hawaiian+pizza',
    calories: '270-320 cal/slice',
    dietary: [],
    tags: {
      hunger: ['normal'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'meat-lovers',
    name: 'Meat Lovers',
    description: 'Pepperoni, sausage, bacon, ham',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=meat+lovers+pizza',
    calories: '380-430 cal/slice',
    dietary: [],
    tags: {
      hunger: ['starving'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'four-cheese',
    name: 'Four Cheese',
    description: 'Mozzarella, parmesan, gorgonzola, fontina',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=four+cheese+pizza',
    calories: '340-390 cal/slice',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'white-pizza',
    name: 'White Pizza',
    description: 'Ricotta, garlic, mozzarella, olive oil',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=white+pizza',
    calories: '290-340 cal/slice',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['light'],
      style: ['classic'],
    },
  },
  {
    id: 'buffalo-chicken',
    name: 'Buffalo Chicken',
    description: 'Spicy buffalo sauce, chicken, ranch drizzle',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=buffalo+chicken+pizza',
    calories: '330-380 cal/slice',
    dietary: [],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['spicy'],
      style: ['adventurous'],
    },
  },
  {
    id: 'prosciutto-arugula',
    name: 'Prosciutto Arugula',
    description: 'Prosciutto, fresh arugula, shaved parmesan',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=prosciutto+arugula+pizza',
    calories: '280-330 cal/slice',
    dietary: ['gluten-free'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'pesto-chicken',
    name: 'Pesto Chicken',
    description: 'Basil pesto, grilled chicken, sun-dried tomatoes',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=pesto+chicken+pizza',
    calories: '310-360 cal/slice',
    dietary: [],
    tags: {
      hunger: ['normal'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'diavola',
    name: 'Diavola',
    description: 'Spicy salami, chili flakes, hot honey',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=diavola+pizza',
    calories: '320-370 cal/slice',
    dietary: [],
    popular: true,
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['spicy'],
      style: ['adventurous'],
    },
  },
  {
    id: 'mediterranean',
    name: 'Mediterranean',
    description: 'Feta, olives, tomatoes, spinach, red onion',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=mediterranean+pizza',
    calories: '240-290 cal/slice',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'sausage-peppers',
    name: 'Sausage & Peppers',
    description: 'Italian sausage, roasted peppers, onions',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=sausage+peppers+pizza',
    calories: '330-380 cal/slice',
    dietary: [],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'goat-cheese-honey',
    name: 'Goat Cheese & Honey',
    description: 'Goat cheese, caramelized onions, honey drizzle',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=goat+cheese+honey+pizza',
    calories: '290-340 cal/slice',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['comfort'],
      style: ['adventurous'],
    },
  },
  {
    id: 'mexican',
    name: 'Mexican',
    description: 'Ground beef, jalapeños, corn, cheddar, salsa',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=mexican+pizza',
    calories: '350-400 cal/slice',
    dietary: ['gluten-free'],
    tags: {
      hunger: ['starving'],
      mood: ['spicy'],
      style: ['adventurous'],
    },
  },
  {
    id: 'seafood',
    name: 'Seafood',
    description: 'Shrimp, calamari, garlic, white wine sauce',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=seafood+pizza',
    calories: '260-310 cal/slice',
    dietary: ['dairy-free'],
    tags: {
      hunger: ['normal'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'carbonara',
    name: 'Carbonara',
    description: 'Pancetta, egg yolk, black pepper, pecorino',
    mode: 'pizza',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=carbonara+pizza',
    calories: '340-390 cal/slice',
    dietary: [],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['comfort'],
      style: ['adventurous'],
    },
  },
];

export const cafeItems: MenuItem[] = [
  {
    id: 'latte',
    name: 'Latte',
    description: 'Smooth espresso with steamed milk',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=latte+coffee',
    popular: true,
    calories: '120-190 cal',
    dietary: [],
    tags: {
      hunger: ['snack'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'americano',
    name: 'Americano',
    description: 'Bold espresso with hot water',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=americano+coffee',
    calories: '5-15 cal',
    dietary: ['vegan', 'gluten-free', 'dairy-free'],
    tags: {
      hunger: ['snack'],
      mood: ['light'],
      style: ['classic'],
    },
  },
  {
    id: 'matcha',
    name: 'Matcha Latte',
    description: 'Japanese green tea with milk',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=matcha+latte',
    calories: '140-240 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'iced-coffee',
    name: 'Iced Coffee',
    description: 'Cold brew over ice',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=iced+coffee',
    popular: true,
    calories: '5-80 cal',
    dietary: ['vegan', 'gluten-free', 'dairy-free'],
    tags: {
      hunger: ['snack'],
      mood: ['light'],
      style: ['classic'],
    },
  },
  {
    id: 'croissant',
    name: 'Butter Croissant',
    description: 'Buttery, flaky French pastry',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=butter+croissant',
    popular: true,
    calories: '230-280 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'sandwich',
    name: 'Artisan Sandwich',
    description: 'Fresh ingredients on sourdough',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=artisan+sandwich',
    calories: '350-550 cal',
    dietary: [],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['comfort'],
      style: ['classic', 'adventurous'],
    },
  },
  {
    id: 'salad',
    name: 'Mixed Greens Salad',
    description: 'Seasonal vegetables, light vinaigrette',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=mixed+greens+salad',
    calories: '150-250 cal',
    dietary: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'],
    tags: {
      hunger: ['normal'],
      mood: ['light'],
      style: ['classic'],
    },
  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    description: 'Espresso with foamed milk, cocoa dusting',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=cappuccino',
    popular: true,
    calories: '80-120 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'flat-white',
    name: 'Flat White',
    description: 'Velvety microfoam with double espresso',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=flat+white+coffee',
    calories: '120-170 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'chai-latte',
    name: 'Chai Latte',
    description: 'Spiced tea with steamed milk',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=chai+latte',
    calories: '190-240 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack'],
      mood: ['comfort'],
      style: ['adventurous'],
    },
  },
  {
    id: 'cortado',
    name: 'Cortado',
    description: 'Equal parts espresso and steamed milk',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=cortado+coffee',
    calories: '40-65 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'cold-brew',
    name: 'Cold Brew',
    description: 'Smooth, less acidic cold extraction',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=cold+brew+coffee',
    calories: '5-15 cal',
    dietary: ['vegan', 'gluten-free', 'dairy-free'],
    tags: {
      hunger: ['snack'],
      mood: ['light'],
      style: ['classic'],
    },
  },
  {
    id: 'mocha',
    name: 'Mocha',
    description: 'Espresso, chocolate, steamed milk, whipped cream',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=mocha+coffee',
    calories: '290-410 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'affogato',
    name: 'Affogato',
    description: 'Vanilla gelato drowned in hot espresso',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=affogato',
    calories: '180-250 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack'],
      mood: ['comfort'],
      style: ['adventurous'],
    },
  },
  {
    id: 'bagel-cream-cheese',
    name: 'Bagel & Cream Cheese',
    description: 'Toasted bagel with herb cream cheese',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=bagel+cream+cheese',
    calories: '290-350 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'avocado-toast',
    name: 'Avocado Toast',
    description: 'Smashed avocado, chili flakes, multigrain',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=avocado+toast',
    popular: true,
    calories: '250-350 cal',
    dietary: ['vegetarian', 'vegan', 'dairy-free'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'acai-bowl',
    name: 'Acai Bowl',
    description: 'Acai blend, granola, fresh berries, honey',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=acai+bowl',
    popular: true,
    calories: '300-450 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['normal'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'quiche',
    name: 'Quiche Lorraine',
    description: 'Bacon, cheese, egg custard in flaky crust',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=quiche+lorraine',
    calories: '350-450 cal',
    dietary: [],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'panini',
    name: 'Italian Panini',
    description: 'Mozzarella, tomato, basil, balsamic glaze',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=italian+panini',
    calories: '380-480 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'breakfast-burrito',
    name: 'Breakfast Burrito',
    description: 'Scrambled eggs, cheese, salsa, black beans',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=breakfast+burrito',
    calories: '450-650 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['starving'],
      mood: ['comfort'],
      style: ['adventurous'],
    },
  },
  {
    id: 'protein-smoothie',
    name: 'Protein Smoothie',
    description: 'Banana, protein powder, almond milk, peanut butter',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=protein+smoothie',
    calories: '280-380 cal',
    dietary: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'muffin',
    name: 'Blueberry Muffin',
    description: 'Fresh baked with wild blueberries',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=blueberry+muffin',
    calories: '350-420 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'granola-yogurt',
    name: 'Granola & Yogurt',
    description: 'Greek yogurt, house granola, seasonal fruit',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=granola+yogurt+parfait',
    calories: '220-320 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['light'],
      style: ['classic'],
    },
  },
  {
    id: 'soup',
    name: 'Tomato Basil Soup',
    description: 'Creamy tomato soup with fresh basil',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=tomato+basil+soup',
    calories: '180-280 cal',
    dietary: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'],
    tags: {
      hunger: ['normal'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'espresso',
    name: 'Espresso',
    description: 'Pure, concentrated shot of Italian coffee',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=espresso+shot',
    calories: '3-5 cal',
    dietary: ['vegan', 'gluten-free', 'dairy-free'],
    tags: {
      hunger: ['snack'],
      mood: ['light'],
      style: ['classic'],
    },
  },
  {
    id: 'macchiato',
    name: 'Macchiato',
    description: 'Espresso marked with foamed milk',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=macchiato+coffee',
    calories: '20-35 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'frappuccino',
    name: 'Frappuccino',
    description: 'Blended iced coffee with whipped cream',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=frappuccino',
    popular: true,
    calories: '320-470 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'tiramisu',
    name: 'Tiramisu',
    description: 'Classic Italian coffee-soaked dessert',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=tiramisu',
    calories: '240-350 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack'],
      mood: ['comfort'],
      style: ['adventurous'],
    },
  },
  {
    id: 'brownie',
    name: 'Chocolate Brownie',
    description: 'Fudgy brownie with chocolate chunks',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=chocolate+brownie',
    calories: '340-450 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'cheesecake',
    name: 'New York Cheesecake',
    description: 'Creamy cheesecake with graham cracker crust',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=new+york+cheesecake',
    calories: '320-420 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'green-smoothie',
    name: 'Green Smoothie',
    description: 'Spinach, mango, banana, coconut water',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=green+smoothie',
    calories: '180-250 cal',
    dietary: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'],
    tags: {
      hunger: ['snack'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'wrap',
    name: 'Mediterranean Wrap',
    description: 'Hummus, grilled veggies, feta, whole wheat wrap',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=mediterranean+wrap',
    calories: '320-420 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'club-sandwich',
    name: 'Club Sandwich',
    description: 'Triple-decker with turkey, bacon, lettuce, tomato',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=club+sandwich',
    popular: true,
    calories: '480-620 cal',
    dietary: [],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'caesar-salad',
    name: 'Caesar Salad',
    description: 'Romaine, parmesan, croutons, Caesar dressing',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=caesar+salad',
    calories: '280-420 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['normal'],
      mood: ['light'],
      style: ['classic'],
    },
  },
  {
    id: 'cinnamon-roll',
    name: 'Cinnamon Roll',
    description: 'Warm, gooey cinnamon roll with cream cheese frosting',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=cinnamon+roll',
    popular: true,
    calories: '420-550 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'fruit-bowl',
    name: 'Fresh Fruit Bowl',
    description: 'Seasonal fresh-cut fruits',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=fresh+fruit+bowl',
    calories: '120-180 cal',
    dietary: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'],
    tags: {
      hunger: ['snack', 'normal'],
      mood: ['light'],
      style: ['classic'],
    },
  },
  {
    id: 'hot-chocolate',
    name: 'Hot Chocolate',
    description: 'Rich cocoa with marshmallows and whipped cream',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=hot+chocolate',
    calories: '250-380 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'iced-tea',
    name: 'Iced Tea',
    description: 'Refreshing brewed tea over ice with lemon',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=iced+tea',
    calories: '0-120 cal',
    dietary: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'],
    tags: {
      hunger: ['snack'],
      mood: ['light'],
      style: ['classic'],
    },
  },
  {
    id: 'poke-bowl',
    name: 'Poke Bowl',
    description: 'Fresh tuna, rice, edamame, avocado, soy glaze',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=poke+bowl',
    calories: '450-580 cal',
    dietary: ['gluten-free', 'dairy-free'],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
  {
    id: 'waffle',
    name: 'Belgian Waffle',
    description: 'Crispy waffle with maple syrup and butter',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=belgian+waffle',
    calories: '380-520 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'egg-sandwich',
    name: 'Egg & Cheese Sandwich',
    description: 'Fried egg, cheddar, toasted English muffin',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=egg+cheese+sandwich',
    calories: '320-420 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['normal', 'starving'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'cookie',
    name: 'Chocolate Chip Cookie',
    description: 'Freshly baked soft cookie with chocolate chips',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=chocolate+chip+cookie',
    calories: '180-250 cal',
    dietary: ['vegetarian'],
    tags: {
      hunger: ['snack'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'oatmeal',
    name: 'Steel-Cut Oatmeal',
    description: 'Hearty oatmeal with brown sugar, berries, nuts',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=steel+cut+oatmeal',
    calories: '250-350 cal',
    dietary: ['vegetarian', 'vegan', 'dairy-free'],
    tags: {
      hunger: ['normal'],
      mood: ['comfort'],
      style: ['classic'],
    },
  },
  {
    id: 'turmeric-latte',
    name: 'Turmeric Latte',
    description: 'Golden milk with turmeric, ginger, honey',
    mode: 'cafe',
    searchUrl: 'https://www.google.com/search?tbm=isch&q=turmeric+latte',
    calories: '140-200 cal',
    dietary: ['vegetarian', 'gluten-free'],
    tags: {
      hunger: ['snack'],
      mood: ['light'],
      style: ['adventurous'],
    },
  },
];

export function getItemsByMode(mode: Mode): MenuItem[] {
  return mode === 'pizza' ? pizzaItems : cafeItems;
}
